Changes

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -76,17 +76,17 @@ runs:
 
    
 
-    - name: Verify Provisioning Profile Placement and UUID
-      shell: bash
-      run: |
-        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
-        if [ -s ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision ]; then
-          echo "Provisioning profile is in place and not empty."
-        else
-          echo "Provisioning profile is missing or empty."
-          exit 1
-        fi
-        chmod +r ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
+    # - name: Verify Provisioning Profile Placement and UUID
+    #   shell: bash
+    #   run: |
+    #     ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
+    #     if [ -s ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision ]; then
+    #       echo "Provisioning profile is in place and not empty."
+    #     else
+    #       echo "Provisioning profile is missing or empty."
+    #       exit 1
+    #     fi
+    #     chmod +r ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
 
 # Might not need this as we're using cocoapods now
     # - name: Resolve package dependencies
